POST https://fakestoreapi.com/carts
Content-Type: application/json

{
  "userId": 5,
  "date": "2020-02-03",
  "products": [
    { 
      "productId": 5, 
      "quantity": 1 
    },
  ],
}

### 

GET https://fakestoreapi.com/carts/11